version: "3.4"

services:
    # Proxy
    nginx:
        container_name: nginx
        image: zeclaudio/nginx:1.0.0
        build:
            context: ./nginx
        ports:
            - 5000:80

    # Linguagens de programação
    # csharp:
    #     container_name: csharp
    #     image: zeclaudio/csharp:1.0.0
    #     build:
    #         context: ./csharp
    #     ports:
    #         - 5010:5000
    # golang:
    #     container_name: golang
    #     image: zeclaudio/golang:1.0.0
    #     build:
    #         context: ./golang
    #     ports:
    #         - 5020:5000
    # nodejs:
    #     container_name: nodejs
    #     image: zeclaudio/nodejs:1.0.0
    #     build:
    #         context: ./nodejs
    #     ports:
    #         - 5030:5000
    python:
        container_name: python
        image: zeclaudio/python:1.0.0
        build:
            context: ./python
        ports:
            - 5040:5000

    # Bancos de dados
    adminer:
        container_name: adminer
        build:
            context: ./adminer
#        restart: always
        ports:
            - 4000:8080
    mysql:
        container_name: mysql
        image: zeclaudio/mysql:1.0.0
        build:
            context: ./mysql
        ports:
            - 4010:3306
        command: --default-authentication-plugin=mysql_native_password
#        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
 