version: "3.4"
services:
    csharp:
        container_name: csharp
        image: zeclaudio/csharp:1.0.0
        build: ./csharp
    golang:
        container_name: golang
        image: zeclaudio/golang:1.0.0
        build: ./golang
    nodejs:
        container_name: nodejs
        image: zeclaudio/nodejs:1.0.0
        build: ./nodejs
    python:
        container_name: python
        image: zeclaudio/python:1.0.0
        build: ./python
 