version: "3.4"
services:
    csharp:
        build:
            target: dev
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes:
            - ./csharp/src:/work
    golang:
        build:
            target: dev
        working_dir: /work
        stdin_open: true
        tty: true
        volumes:
            - ./golang/src:/work
    nodejs:
        build:
            target: dev
        working_dir: /work
        stdin_open: true
        tty: true
        volumes: 
            - ./nodejs/src:/work
    python:
        build:
            target: dev
        working_dir: /work
        stdin_open: true
        tty: true
        volumes: 
            - ./python/src:/work
