version: "3"
services: 
    nodejs:
        container_name: nodejs
        image: zeclaudio/nodejs:1.0.0
        build: ./nodejs
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes: 
        - ./nodejs/src/:/work
        ports:
            - 5000:5000