FROM node:current-alpine
#  as install

# WORKDIR /work/

# COPY ./src/package.json /work/package.json
# RUN npm install

# ####################

# FROM install as debug

# RUN npm install -g nodemon

# COPY ./src/ /work/

# ENTRYPOINT [ "nodemon", "--inspect=0.0.0.0", "./server.js" ]

# ####################

# FROM install as prod

# COPY ./src/ /work/

# CMD node .
